apiVersion: scheduling.kcp.dev/v1alpha1
kind: Location
metadata:
  annotations:
    kcp.dev/cluster: root:my-org
  label:
    color: green
  name: green
spec:
  instanceSelector: {}
  resource:
    group: workload.kcp.dev
    resource: synctargets
    version: v1alpha1